# Generated by Django 5.1.2 on 2024-10-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_update',
        ),
    ]
